# Generated by Django 3.0.14 on 2023-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True)),
                ('completed_time', models.DateTimeField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
